# Generated by Django 3.2.8 on 2021-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0005_auto_20211125_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='eng_yaxshi',
            name='biladigan_dasturlash_tili',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='familiyasi',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='holati',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='ismi',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='malumoti',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='rasmi',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eng_yaxshi',
            name='yoshi',
            field=models.IntegerField(null=True),
        ),
    ]
